function value = query(bundle, w, sets)
% w and sets is the valuaition function generated by submodular_func
% Bundle is a vector in [m]. 
% The goal of this function is to query the generated submodular function

vector = sum(sets(:,bundle),2);
vector = (vector > 0);
value = sum(w.*vector);

end